// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebsmxegthecrfrcpdfnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVic214ZWd0aGVjcmZyY3BkZm5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTAyNTksImV4cCI6MjA2MTQyNjI1OX0.Hmap2vRGrhnA_OHr2uSSRHe2U2B1CFNCgTM84_n-_w0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);